In [1]:
import numpy as np

1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [14]:
a = np.array([[1, 2, 3]], float)
b = np.array([[0, -1, 12]], float)
print(a)
print(b)

[[1. 2. 3.]]
[[ 0. -1. 12.]]


In [17]:
print(a[0, 2])
print(b[0, 0])

3.0
0.0


In [18]:
print(a.shape)

(1, 3)


In [19]:
c = np.array([[0], [-1], [12]], float)
print(c)
print(c.shape)

[[ 0.]
 [-1.]
 [12.]]
(3, 1)


In [20]:
d = a * 2
print(d)

[[2. 4. 6.]]


In [21]:
e = a + b
print(e)

[[ 1.  1. 15.]]


In [22]:
e = np.subtract(a, b)
print(e)

[[ 1.  3. -9.]]


In [23]:
e = a - b
print(e)

[[ 1.  3. -9.]]


In [24]:
f = a.transpose()
print(a)
print(f)

g = c.transpose()
print(c)
print(g)

[[1. 2. 3.]]
[[1.]
 [2.]
 [3.]]
[[ 0.]
 [-1.]
 [12.]]
[[ 0. -1. 12.]]


In [27]:
i = np.dot(f, g)
print(i)
f.shape, g.shape
j = np.dot(g, f)
print(j)
g.shape, f.shape

[[ 0. -1. 12.]
 [ 0. -2. 24.]
 [ 0. -3. 36.]]
[[34.]]


((1, 3), (3, 1))

In [28]:
u = np.array([1, 2, 3, 4, 5], float)
v = np.array([0, 9, 8, 7, 6], float)
print(u)
print(v)

[1. 2. 3. 4. 5.]
[0. 9. 8. 7. 6.]


In [36]:
w = np.dot(u, v)
print(w)
w = np.dot(v, u)
print(w)

x = np.inner(u, v)
print(x)
x = np.inner(v, u)
print(x)

y = np.outer(u, v)
print(y)
y = np.outer(v, u)
print(y)

100.0
100.0
100.0
100.0
[[ 0.  9.  8.  7.  6.]
 [ 0. 18. 16. 14. 12.]
 [ 0. 27. 24. 21. 18.]
 [ 0. 36. 32. 28. 24.]
 [ 0. 45. 40. 35. 30.]]
[[ 0.  0.  0.  0.  0.]
 [ 9. 18. 27. 36. 45.]
 [ 8. 16. 24. 32. 40.]
 [ 7. 14. 21. 28. 35.]
 [ 6. 12. 18. 24. 30.]]


2. Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.

Так как $A \cdot E = E \cdot A = A$, а по определению обратной матрицы $A \cdot A^{-1} = E$, то $E = E^{-1}$

$(5E)^{-1} = 5^{-1} \cdot E^{-1} = 0.2E = \left(
\begin{array}{cccc}
0.2 & 0 & 0 & 0 & 0\\
0 & 0.2 & 0 & 0 & 0\\
0 & 0 & 0.2 & 0 & 0\\
0 & 0 & 0 & 0.2 & 0\\
0 & 0 & 0 & 0 & 0.2
\end{array}
\right)
$

In [2]:
a = np.array([[5, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 5, 0, 0], [0, 0, 0, 5, 0], [0, 0, 0, 0, 5]])
p = np.linalg.inv(a)
print(p)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]
